<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RaceSeeder extends Seeder
{
    public function run()
    {
        $races = [
            [
                'id' => 1,
                'slug' => 'cachorro-beagle',
                'description' => 'Cachorro Beagle',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/beagle-welpen-zu-verkauf-alle-welpen-300x300.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'slug' => 'cachorro-bichon-frise',
                'description' => 'Cachorro Bichon Frise',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/bichon-frise-puppies-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'slug' => 'cachorro-border-collie',
                'description' => 'Cachorro Border Collie',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/oio.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'slug' => 'cachorro-boston-terrier',
                'description' => 'Cachorro Boston Terrier',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/boster-t-1-bansky-1-296x296x7x0x282x296x1751319054.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'slug' => 'boxer-cachorro',
                'description' => 'Cachorro Boxer',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/beast-1-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'slug' => 'cachorro-boyero-de-berna',
                'description' => 'Cachorro Boyero de Berna',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/koda-1-282x303x0x3x282x296x1717856185.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'slug' => 'cachorro-bulldog-frances',
                'description' => 'Cachorro Bulldog francés',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/fn-new-9-282x351x0x27x282x296x1751253513.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'slug' => 'cachorro-bulldog-ingles',
                'description' => 'Cachorro Bulldog inglés',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/ii.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'slug' => 'cachorro-cane-corso',
                'description' => 'Cachorro Cane Corso',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/can.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'slug' => 'caniche-cachorro',
                'description' => 'Cachorro Caniche',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/toy_poodle__lovers-20250627-0044-296x296x9x0x282x296x1751359982.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'slug' => 'chihuahua-cachorro',
                'description' => 'Cachorro Chihuahua',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/rose1-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'slug' => 'cachorro-dachshund',
                'description' => 'Cachorro Dachshund',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/maisy5-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'slug' => 'cachorro-de-agua-espanol',
                'description' => 'Cachorro De agua espanol',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/pixel_thewaterdog-20250814-0009-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'slug' => 'cachorro-galgo-espanol',
                'description' => 'Cachorro Galgo espanol',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/numa-elgalgo-20250815-0001-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'slug' => 'cachorro-golden-retriever',
                'description' => 'Cachorro Golden Retriever',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/sergio-male-4-330x296x24x0x282x296x1717854723.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'slug' => 'cachorro-ibiza-hound',
                'description' => 'Cachorro Ibiza hound',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/austin-the-beezer-20250815-0007-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'slug' => 'cachorro-labrador',
                'description' => 'Cachorro Labrador',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/labrador4-4-296x296x7x0x282x296x1751362269.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'slug' => 'cachorro-maltese',
                'description' => 'Cachorro Maltese',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/maltese.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'slug' => 'maltipoo-cachorro',
                'description' => 'Cachorro Maltipoo',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/maltipoo-zelda-6-282x340x0x22x282x296x1751253996.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'slug' => 'cachorro-pastor-aleman',
                'description' => 'Cachorro Pastor alemán',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/german-shepherd-1-282x331x0x17x282x296x1751330528.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'slug' => 'pomerania-cachorro',
                'description' => 'Cachorro Pomerania',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/billy2-18-35-19-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'slug' => 'cachorro-presa-canario',
                'description' => 'Cachorro Presa canario',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/chapo_de_earthquake_kennels-20250815-0003-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'slug' => 'pug-cachorro',
                'description' => 'Cachorro Pug',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/rio-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'slug' => 'cachorro-rottweiler',
                'description' => 'Cachorro Rottweiler',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/rottweilers-22-282x352x0x28x282x296x1751361576.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'slug' => 'cachorro-shiba-inu',
                'description' => 'Cachorro Shiba Inu',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/shiba-inu-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'slug' => 'cachorro-yorkie',
                'description' => 'Cachorro Yorkie',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/yorkie-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'slug' => 'cachorros-goldendoodle',
                'description' => 'Cachorros Goldendoodle',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/goldendoodle-3-1-282x352x0x28x282x296x1751358336.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'slug' => 'cachorros-pastor-australiano',
                'description' => 'Cachorros Pastor Australiano',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/aussi-d-12-18-296x296x7x0x282x296x1751249897.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'slug' => 'cachorros-pomsky',
                'description' => 'Cachorros Pomsky',
                'imagen' => json_encode(['/wp-content/uploads/2025/08/pomsky1-24-300x300.webp']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('races')->insert($races);
    }
}
